# ============================================================================
# .github/workflows/ci.yml - GitHub Actions CI/CD Pipeline
# ============================================================================
name: LSuite CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

# Set working directory for all jobs
defaults:
  run:
    working-directory: LiquidSuite

jobs:
  # ===========================
  # Lint and Code Quality
  # ===========================
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('LiquidSuite/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
          pip install -r requirements.txt
      
      - name: Run Black (code formatter check)
        run: black --check lsuite/ app.py config.py || true
        continue-on-error: true
      
      - name: Run Flake8 (linting)
        run: flake8 lsuite/ app.py config.py --max-line-length=100 --exclude=migrations || true
        continue-on-error: true

  # ===========================
  # Unit Tests
  # ===========================
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: lsuite_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('LiquidSuite/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      
      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U test_user; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
      
      - name: Initialize database
        env:
          DATABASE_URL: postgresql://test_user:test_password@localhost:5432/lsuite_test
          CELERY_BROKER_URL: redis://localhost:6379/0
          CELERY_RESULT_BACKEND: redis://localhost:6379/0
          SECRET_KEY: test-secret-key-for-ci
          FLASK_ENV: testing
        run: |
          python -c "from lsuite import create_app; from lsuite.extensions import db; app = create_app('testing'); app.app_context().push(); db.create_all()"
      
      - name: Run tests with coverage
        env:
          DATABASE_URL: postgresql://test_user:test_password@localhost:5432/lsuite_test
          CELERY_BROKER_URL: redis://localhost:6379/0
          CELERY_RESULT_BACKEND: redis://localhost:6379/0
          SECRET_KEY: test-secret-key-for-ci
          FLASK_ENV: testing
        run: |
          pytest tests/ -v --cov=lsuite --cov-report=xml --cov-report=term
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./LiquidSuite/coverage.xml
          flags: unittests
          name: codecov-lsuite
        continue-on-error: true

  # ===========================
  # Security Scan
  # ===========================
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety bandit
      
      - name: Run Safety (dependency vulnerabilities)
        run: safety check --json || true
        continue-on-error: true
      
      - name: Run Bandit (security issues)
        run: bandit -r lsuite/ -f json || true
        continue-on-error: true

  # ===========================
  # Build Docker Image
  # ===========================
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [lint, test]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./LiquidSuite
          file: ./LiquidSuite/Deployment/Dockerfile
          push: false
          tags: lsuite:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Test Docker image
        working-directory: .
        run: |
          docker run --rm lsuite:${{ github.sha }} python -c "from lsuite import create_app; app = create_app('production'); print('✓ App imports successful')"
