# ============================================================================
# init-database.yml - Initialize Production Database
# ============================================================================
name: Initialize Database

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Database action to perform'
        required: true
        default: 'init-and-seed'
        type: choice
        options:
          - init
          - seed
          - check
          - init-and-seed

jobs:
  database-action:
    name: Database Management
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: LiquidSuite
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Database Action
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SQLALCHEMY_DATABASE_URI: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FLASK_ENV: production
        run: |
          ACTION="${{ github.event.inputs.action }}"
          echo "🔧 Running database action: $ACTION"
          
          case $ACTION in
            init)
              echo "📊 Creating database tables..."
              python scripts/init_db.py init
              ;;
            seed)
              echo "🌱 Seeding transaction categories..."
              python scripts/seed_categories.py seed
              ;;
            check)
              echo "🔍 Checking database status..."
              python scripts/init_db.py check
              ;;
            init-and-seed)
              echo "📊 Creating database tables..."
              python scripts/init_db.py init
              echo ""
              echo "🌱 Seeding transaction categories..."
              python scripts/seed_categories.py seed
              echo ""
              echo "🔍 Verifying database..."
              python scripts/init_db.py check
              ;;
          esac
          
          echo ""
          echo "✅ Database action completed successfully!"
